README.md
Better to take the default setting in users' local kubeconfig. Easy to get started when trying in local Minikube.
=> Remove namespace specification from the README examples

couler/__init__.py
Currently this is missing so users won't be able to call the following outside of the project folder:
```
import couler.argo as couler
from couler.argo_submitter import ArgoSubmitter
```
We will clean up and seal the interfaces later once we add support for other engines.
=> Add missing __init__ file to expose Argo implementation

couler/steps/tensorflow.py, couler/tests/tensorflow_step_test.py
The core part of couler provides the basic workflow operation, in addition, we hope to build a step lib to help end-users to start a job easily like the TensorFlow, PyTorch, or Spark job, etcs.  In this pr, we provide the TensorFlow job submission, in the future, we are so welcome other PRs for PyTroch, MPI, etc. 
as mentioned above
No.
Yes
=> [feat] Provide the Couler steps to support different jobs like Tensorflow job

couler/argo.py, couler/core/templates/__init__.py, couler/core/templates/artifact.py, couler/core/templates/container.py, couler/tests/artifact_test.py
Currently, only OSS Artifacts are supported. This PR adds an `S3` Artifact sub-class.
I still haven't added tests for this, but I wanted to open this PR to discuss how this type of change is supposed to be implemented. Is the method in the first commit, where I duplicate code between `OSSArtifact` and `S3Artifact`, acceptable? Alternatively, is the second commit, where I create a `TypedArtifact` subclass better?
=> Enable S3 Artifact usage

docs/couler-api-design.md
Hi community, 
We are opening this PR to share our thoughts on supporting multiple workflow engines. We'd appreciate any feedback and suggestions. In addition, if you are interested in contributing either a new backend or functionalities of the existing backend, please let us know in this pull request.
=> [RFC] Add initial design doc for core Couler API 

couler/core/syntax/__init__.py, couler/core/syntax/volume.py, couler/core/templates/volume_claim.py, couler/core/templates/workflow.py, couler/tests/argo_test.py
Argo [has support for creating per-workflow PVCs](https://github.com/argoproj/argo/blob/master/examples/volumes-pvc.yaml), allowing users to create a PVC which is terminated once the workflow is finished.  This pull request adds couler support for creating a transient PVC that can be used within a workflow.
For many ML applications, it's convenient to place data on a filesystem for processing over the course of multiple workflow steps.  This change makes it much easier to create a temporary mount for a single workflow.
This PR adds a single additional user-facing function, a helper function for adding a pvc to a workflow:
```py
from couler.core.syntax import create_workflow_volume
```
The following workflow can be used to validate this change.  It creates a workflow volume, mounts it to …
=> Add support for transient PVCs in workflows

ADOPTERS.md, README.md
Hi community,
This PR adds a document `ADOPTERS.md` that contains an initial list of organizations who are using Couler. If you'd like to add your organization to the list, please comment here or send us a pull request that modifies `ADOPTERS.md`. Thanks everyone for your continuous support and contributions!
cc @couler-proj/couler-team  @davidhershey @vishnu2kmohan @binarycrayon @JPZ13 @FogDong @gaocegege
=> docs: Add initial list of Couler adopters

docs/couler-tekton-design.md
Chore(docs): add tekton backend design doc
Ref: #44
=> docs: Add Tekton backend design doc

go/couler/optimization/optimization.go, go/couler/optimization/optimization_test.go
Fix incorrect optimization package name. cc @Yancey1989 
Package name is incorrect.
No.
=> fix: Fix incorrect optimization package name

couler/core/proto_repr.py, couler/core/run_templates.py, couler/tests/proto_repr_test.py
`couler.run_job` can generate protobuf formated structure for future use.
=> feat: add gen proto for run_job

docs/couler-step-zoo.md
Add document on Couler Step Zoo. Related issue https://github.com/couler-proj/couler/issues/67.
cc'ing @couler-proj/couler-team @xinbinhuang @andreyvelich @FogDong @gaocegege @davidhershey @vishnu2kmohan @JPZ13 @inohmonton99 and others who might be interested to take a look and share feedback.
This document introduces the Couler Step Zoo, which consists of a collection of pre-defined and reusable steps that can
be used directly as part of a workflow defined using Couler.
No.
Not applicable.
=> docs: Add document on Couler Step Zoo

couler/core/proto_repr.py, couler/tests/proto_repr_test.py, proto/couler.proto
Add artifact secret details in the proto description.
The protobuf representation needs the secret value details in order to submit jobs to K8S.
No.
Unit tests are added.
=> feat: Add artifact secret detail in proto

go/couler/proto/couler/v1/proto.go, go/couler/proto/proto.go
fix `proto.go` file path to fit the package name.
=> fix: proto.go file path

.github/workflows/build.yml
See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/. This would allow maintainers to trigger builds on a branch without creating a PR.
=> ci: Allow manual trigger of GitHub Actions builds

couler/core/proto_repr.py, couler/tests/proto_repr_test.py
Currently `command: python` is appended to step proto when this step contains manifest (resource type), which is incorrect and this PR fixes it.
=> fix: Avoid appending command  to proto when step contains manifest

couler/core/templates/script.py, couler/tests/workflow_basic_test.py
Support call `couler.run_script` with string source code.
To support generating dynamic python function calls.
No.
A test case is included.
=> feat: support run_script with string source code

couler/core/proto_repr.py, couler/core/run_templates.py, go/couler/conversion/argo_workflow.go, proto/couler.proto
Environment variables are always string typed in any OS, so change the protobuf message to the string type. Previous `Any` type may introduce complexity and bugs.
No.
The current unit tests can cover the change.
=> feat: env value use string type

RELEASE.md
It's easy for this doc to get out of date so let's use the releases page for the source of truth.
=> docs: Redirect to GitHub releases page for release document

go/couler/commands/submit.go, go/couler/submitter/argo_submitter.go, go/couler/submitter/argo_submitter_test.go
Support in-cluster configuration in Go submitter and reuse `submitter.New` instead of previously unnecessarily exporting a struct in https://github.com/couler-proj/couler/pull/170.
No.
=> feat: Support in-cluster configuration in Go submitter

couler/core/templates/container.py, couler/tests/test_data/artifact_passing_golden.yaml
With this change, artifacts are not automatically injected in `container.args` or `script.args`. This is causing issues in all of our workflows that pass artifacts since the path of the artifact is getting passed in as arguments to `command`.
Before this change, artifacts were getting injected as args like so:
```yaml
command:
- python
args:
- '{{inputs.parameters.para-train-model-0}}' # value is `main.py`
- '{{inputs.artifacts.output-local-36e25910}}'
```
After this change, the artifact is no longer injected:
```yaml
command:
- python
args:
- '{{inputs.parameters.para-train-model-0}}' # value is `main.py`
```
Without this change, any command or script (much like above) that didn't expect an artifact path as an argument failed.
Note that even without [this …
=> fix: Do not inject artifacts in args

.github/workflows/build.yml
We now have centralized control over admin access so `workflow_dispatch` does not seem to work anymore. This PR enables builds on dev branches to facilitate development/debugging.
=> build: Allow build on dev-* branches

couler/core/proto_repr.py, couler/core/run_templates.py, couler/tests/proto_repr_test.py, integration_tests/mpi_example.py
This PR includes the following changes:
* Added missing `action` when converting steps defined via `run_job()` to IR. 
* Added integration test for submitting MPIJob via Go submitter.
=> feat: Support IR conversion/submission from Kubeflow steps

couler/core/proto_repr.py
Fix `proto_repr.py` working with protobuf 3.7.1
=> fix: proto repr working with protobuf 3.7.1

couler/core/states.py, couler/tests/proto_repr_test.py
Fix compatibility issues when updating from older versions of couler.
Some runtime Python environment may have different versions of protobuf Python runtime installed which may cause error.
No.
Current unit tests will cover the changes.
=> fix: compatibility when importing proto

couler/core/run_templates.py
We need to skip Couler proto message build when importing fails to be compatible with previous use cases.
No.
The current unit tests will cover these changes.
=> fix: skip proto build when proto import fails

couler/core/config.py, couler/core/templates/workflow.py, couler/tests/workflow_basic_test.py
Hi,
This PR adds [ServiceAccount](https://argoproj.github.io/argo-workflows/service-accounts/) in the workflow config. Users can submit workflows with their own k8s ServiceAccuonts now.
```python
couler.config_workflow(
service_account='dinever',
)
```
Some organizations use non-default service accounts to run Argo workflows for fine-grained permission control.
No
Unit test
=> feat: Support ServiceAccount for workflows

couler/core/templates/workflow.py, couler/tests/workflow_basic_test.py, integration_tests/flip_coin_security_context_example.py, scripts/integration_tests.sh
This PR adds support for specifying a workflow-level [`securityContext`](https://argoproj.github.io/argo-workflows/fields/#podsecuritycontext) to any argo workflow.
Many kubernetes clusters enforce a pod security policy. This requires argo workflows to include the appropriate workflow-level [securityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) in order to run with the appropriate permissions.
```python
couler.states.workflow.set_security_context(security_context={
"fsGroup": 2000,
"runAsNonRoot": True,
"runAsUser": 1000,
})
```
```console
☸️  minikube (argo) via 🐍 v3.8.5 (venv) 
🚩 python3 main.py
INFO:root:Found local kubernetes config. Initialized with kube_config.
INFO:root:Checking workflow name/generatedName main-
INFO:root:Submitting workflow …
```
=> feat: Add security context support

scripts/integration_tests.sh
The test times out on CI. To be investigated later.
=> build: Temporarily disabled MPIJob integration test

.isort.cfg, couler/argo.py, couler/argo_submitter.py, couler/core/config.py, couler/core/run_templates.py, couler/core/states.py, couler/core/templates/container.py, couler/core/templates/template.py, couler/tests/__init__.py, couler/tests/workflow_basic_test.py, examples/default_submitter.py, examples/hello_world.py, requirements.txt
Fixes/fulfills #214 and #209 
Automatically applies salt to workflow names. The salting function can be changed.
Avoids naming clashes between different runs of the same workflow. 
Enables `envFrom` fields on containers.
Tested with live workflows.
=> feat: Implemented `envFrom` field for containers + saving given client config + automatic naming salt for workflow names

couler/core/templates/volume_claim.py, couler/tests/argo_test.py
The proposal would make the `VolumeClaimTemplate`s size and `accessModes` dynamic by letting the user input them so they would not be hardcoded.
#210 
Working on a workflow I noticed that my workflow would require the `accessModes` to be `ReadWriteMany`, not `ReadWriteOnce`. `ReadWriteOnce` was hardcoded, I thought that it would be better if the workflow creator could set it the way she/he needs it. Same for the `size`.
Users would have to write 3 arguments to the VolumeClaimTemplate instead of one. 
Previous version:
`volume = VolumeClaimTemplate("workdir")`
Updated version:
`volume = VolumeClaimTemplate("workdir", ['ReadWriteMany'], '1Gi')`
The testing was done by abiding [Coulers instructions](https://github.com/couler-proj/couler/blob/0b33ac61588d8dbfe4ccbdf618de2572cf776ce2/CONTRIBUTI …
=> fix: Volume_claim to dynamic

README.md, docs/README.md
This Slack workspace is not active. Argo has also switched to reuse CNCF Slack workspace as well.
I will also post a message on the Slack workspace to let others know.
=> docs: Remove link to Slack workspace

.github/workflows/build.yml
Fixed the following issue:
```
Warning  FailedScheduling  21s   default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
Normal   Scheduled         21s   default-scheduler  Successfully assigned argo/workflow-controller-85f776c7ff-vqfbj to minikube
Normal   Pulling           20s   kubelet            Pulling image "argoproj/workflow-controller:v2.12.6"
Warning  FailedScheduling  20s   default-scheduler  AssumePod failed: pod 94efa52a-f88a-4ca2-a2f1-319c2bf4d167 is in the cache, so can't be assumed
```
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> ci: Bump minikube version and fix integration build

README.md
This fixes the following issue:
```
Collecting git+https://github.com/couler-proj/couler@v0.1.1rc8-stable
Cloning https://github.com/couler-proj/couler (to revision v0.1.1rc8-stable) to /tmp/pip-req-build-yj7xv69q
Collecting Deprecated
Downloading Deprecated-1.2.12-py2.py3-none-any.whl (9.5 kB)
...
Successfully built couler wrapt
Installing collected packages: wrapt, Deprecated, websocket-client, docker, pyyaml, oauthlib, requests-oauthlib, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, python-dateutil, urllib3, kubernetes, pyaml, couler
Attempting uninstall: pyyaml
Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial …
```
=> fix: Add `--ignore-installed` and `python3 -m pip` when installing Python package

couler/core/syntax/__init__.py, couler/core/syntax/toleration.py, couler/core/templates/toleration.py, couler/core/templates/workflow.py, couler/tests/argo_test.py
This adds `tolerations:` support to couler Workflows.
Tolerations are supported by Argo, but not by Couler.
In our case, we taint our GPU nodes so CPU-only jobs cannot be assigned to them. This PR will allow us to run workflows on these tainted nodes.
Yes, it adds an `add_toleration()` method and a `Toleration` class.
Unit tests were added, and this PR was based loosely on a similar PR: https://github.com/couler-proj/couler/pull/238
=> feat: Adding toleration support

couler/argo.py, couler/core/templates/artifact.py, couler/core/templates/secret.py, couler/tests/artifact_test.py, couler/tests/secret_test.py
S3Artifact endpoint can be set to be insecure (HTTP); Secrets do not have the "namespace: default" entry when no namespace is specified. This enables the use of S3Artifacts when running workflow in a namespace other than "default".
1. Added a new argument `insecure` to the `create_s3_artifact` function.
2. Secret yaml file does not put the "namespace: default" entry when no namespace is specified.
1. S3Artifact Endpoint can be HTTP now
3. Secret yaml file does not put the "namespace: default" entry when no namespace is specified. This enables the use of S3Artifacts to be used when workflow is submitted to a namespace other than "default". Previously it would cause an error where the secret created by the S3Artifact always has the "namespace: default" entry no matter which namespace the …
=> feat: Enable insecure endpoint for S3Artifacts and S3Artifact usage when workflow is submitted to a namespace other than "default"
