couler-proj/couler

AUTHORS
CONTRIBUTORS

Add AUTHORS and CONTRIBUTORS files

---

.github/workflows/build.yml
.isort.cfg
couler/argo.py
couler/core/templates/output.py
couler/core/templates/workflow.py
couler/core/workflow_validation_utils.py
couler/tests/argo_test.py
couler/tests/map_test.py
couler/tests/pyfunc_test.py
couler/tests/workflow_basic_test.py
couler/tests/workflow_validation_utils_test.py
requirements.txt

Set up GitHub Actions and fix pre-commit checks

---

.github/workflows/build.yml
README.md

Signed-off-by: terrytangyuan terrytangyuan@gmail.com

Add GitHub Actions status badge

---

.github/workflows/build.yml

This is to prepare for the integration tests on k8s.

Set up Minikube on GitHub Actions

---

.github/workflows/build.yml
couler/argo.py
couler/core/templates/workflow.py
couler/tests/workflow_basic_test.py
integration_tests/dag_example.py
integration_tests/flip_coin_example.py
manifests/quick-start-minimal-argo-v2.10.0.yaml

Add integration test example with Argo

---

README.md

Add initial README.md with examples

---

integration_tests/dag_example.py
integration_tests/flip_coin_example.py
scripts/validate_workflow_statuses.sh

Add missing copyright headers for new files

---

.github/workflows/build.yml
CONTRIBUTING.md

Add contributing guide and clean build.yml

---

couler/argo_submitter.py

An example output after this PR:
```
(test) ➜  couler git:(master) ✗ python demo.py
INFO:root:Found local kubernetes config. Initialized with kube_config.
INFO:root:Checking workflow name/generatedName demo-
INFO:root:Submitting workflow to Argo
INFO:root:Workflow demo-m4cq6 has been submitted!
```

Add more logging when running with ArgoSubmitter

---

setup.py

There's currently no CLI and step zoo so we remove them from the description for now.

Update package descriptions in setup.py

---

couler/core/syntax/loop.py

Remove hard-coded kind in map()

---

.github/workflows/build.yml
couler/core/step_update_utils.py
couler/core/syntax/exit_handler.py
couler/tests/argo_test.py
integration_tests/dag_example.py

Support exit handler for DAG-based workflows

---

integration_tests/dag_example.py

Reformat the comments on DAG shape in DAG example
It would look better and consistent with existing README.md.
No.
It's part of the current CI and we only modified the comments.

Reformat the comments on DAG shape in DAG example

---

README.md

Add a badge to twitter handle.
We can announce updates on Twitter to promote the project.
No
Just a simple change in README.

Add badge for Twitter handle

---

couler/core/templates/job.py
couler/core/utils.py

convert bool to string

---

.github/workflows/build.yml
manifests/quick-start-minimal-argo-v2.10.2.yaml

Signed-off-by: Yudi Xue <10211+binarycrayon@users.noreply.github.com>
- Added a argo-2.10.2 manifest
- reference the new manifest in github action
- fixes issue #52

[update-argo-dep] Update integ test dep to argo v2.10.2, fixes #52

---

README.md

Add link to slides for Argo community meeting.
Useful for community members.
No.
Not necessary.

Add link to slides for Argo community meeting

---

couler/argo.py
requirements.txt

* Fix incorrect ApiException import for k8s python v11.0.0+.
* Update requirements to kubernetes>=11.0.0.
The location for `ApiException` has been moved. This change is necessary to fix error `AttributeError: module 'kubernetes.client.api_client' has no attribute 'ApiException'`.
No.
Tested as part of the CI.

Fix incorrect ApiException import for k8s python v11.0.0

---

couler/argo.py
requirements.txt

Signed-off-by: Yudi Xue <10211+binarycrayon@users.noreply.github.com>
* Specify argo-workflows==3.5.0 in requiremets
* uncomment validate-with-argo-sdk
fixes #49
No
Part of unit test suite

[enable-argo-sdk] update requirements and re-enable argo-workflows, fixes #49

---

couler/_version.py

This PR bumps up the version to 0.1.1.rc6 to prepare for release. List of changes since last release: https://github.com/couler-proj/couler/compare/v0.1.1rc5...1278f73
Incorporate a couple of fixes and enhancements.
No.
Tested as part of the CI.

Bump up version to 0.1.1.rc6 to prepare for release

---

couler/steps/katib.py
couler/tests/katib_step_test.py

This PR adds the support of Katib experiment as a pre-defined Couler step.
Part of the efforts to provide pre-defined steps for Kubeflow jobs.
No.
Added unit test.

Support Katib experiment as a pre-defined Couler step

---

couler/tests/artifact_test.py
couler/tests/test_data/artifact_passing_golden.yaml

Change bucket name 'anttest' in tests to 'test-bucket'.
This will make the code base more community friendly.
No.

Change bucket name 'anttest' in tests to 'test-bucket'

---

couler/core/templates/artifact.py
couler/core/templates/output.py
couler/core/utils.py

Close #30.
Code style changes.
No.
Unit test.

fix(couler): move import statements to the top

---

docs/README.md
docs/TEMPLATE.md

Add template for design proposals.
To help contributors write design docs in a consistent format.
No.
Not necessary.

docs: Add template for design proposals

---

couler/steps/pod_utils.py
couler/steps/pytorch.py
couler/steps/tensorflow.py
couler/steps/utils.py
couler/tests/pytorch_step_test.py

* Support PyTorchJob as a pre-defined Couler step
* Refactored reusable code to `couler.steps.pod_utils.py`
To support Kubeflow/PyTorchJob as a Couler step. Part of https://github.com/couler-proj/couler/issues/38.
No.
Unit tests added.

feat: Support PyTorchJob as a pre-defined Couler step

---

couler/argo_submitter.py

Print namespace after successful workflow submission.
Thanks @JPZ13 for pointing this out. Adding this would avoid confusion to users who might look for the submitted workflows. in `argo` namespace that's commonly seen in Argo Workflow examples.
No.
Tested in CI.

chore: Print namespace after successful workflow submission

---

.github/semantic.yml

Add config for semantic PR check: https://github.com/zeke/semantic-pull-requests#configuration
It's unnecessary to check whether commits messages are semantic since new contributors may not have knowledge in how to address the issue and maintainers can just modify the PR title to make the PR semantic.
No.
Not necessary.

ci: Add config for semantic PR check

---

couler/steps/mpi.py
couler/steps/pod_utils.py
couler/tests/mpi_step_test.py

* Support MPIJob as a pre-defined Couler step
To support Kubeflow/MPIJob as a Couler step. Part of https://github.com/couler-proj/couler/issues/38.
No.
Unit tests added.

feat: Support MPIJob as a pre-defined Couler step

---

RELEASE.md

Add release notes.
This would be helpful for community to view and search from the past releases.
No.
Not necessary.

docs: Add release notes

---

ADOPTERS.md

docs: Add Onepanel to ADOPTERS.md

---

ADOPTERS.md

docs: Update Onepanel Entry

---

couler/core/utils.py

Fix invalid name for when function is invoked at module-level.
Currently, if we submit a workflow via `python -m integration_tests.an_example`, we would obtain a step name `<module>` which will be invalid syntax for k8s with the following error message when the workflow is submitted:
```
invalid spec: spec.templates[1].name: '<module>' is invalid: name must consist of alpha-numeric characters or '-', and must start with an alpha-numeric character (e.g. My-name1-2, 123-NAME)
```
This PR fixes the above issue.
No.
Part of the test suite.

fix: Fix invalid step name when function is invoked at module-level

---

couler/core/run_templates.py
couler/core/templates/container.py
couler/tests/argo_test.py

Support container-level working directory in `run_container()`.
Fixes #82,  feature request from @inohmonton99.
Yes, introduced a new parameter for `run_container()`.
Test case added.

feat: Support container-level working directory in run_container()

---

couler/core/templates/artifact.py

Make secret, bucket, and endpoint optional for artifacts. 
Some users may inject these fields from their own configurations instead of specifying them in the workflow spec.
cc @inohmonton99.
No, for user-facing functions like `create_s3_artifact`, these fields were actually already optional but the underlying implementation throws exception `need to input the correct config for s3`. 
Covered in unit tests.

feat: Make secret, bucket, and endpoint optional for artifacts

---

scripts/integration_tests.sh
scripts/validate_workflow_statuses.sh

Adding `set -e` to exit immediately if any of the workflow has failed.
This is to fail fast and avoid the waste of CI resources.
No.
Tested in CI.

ci: Exit immediately if any of the workflow has failed

---

README.md

Add links to CNCF and LF AI landscapes where Couler has been included.
It's useful for community to see the positioning of Couler in the landscapes.
No.
Not necessary.

docs: Add links to CNCF and LF AI landscapes

---

couler/core/run_templates.py
couler/core/templates/container.py
couler/tests/argo_test.py

Support specifying step-level node selector.
Fixes #88.
No.
Test case added.

feat: Support specifying step-level node selector

---

.github/workflows/build.yml
couler/steps/mpi.py
couler/tests/mpi_step_test.py
integration_tests/mpi_example.py
manifests/mpi-operator.yaml
scripts/validate_workflow_statuses.sh

* Add MPIJob Couler step integration test.
* Fix typo in replica status field for condition checking.
To make sure the existing integration works.
No. 
Tests are added.

ci: Add MPIJob Couler step integration test

---

couler/steps/mpi.py
couler/steps/pytorch.py
couler/steps/tensorflow.py
couler/tests/mpi_step_test.py
couler/tests/pytorch_step_test.py
couler/tests/tensorflow_step_test.py

Fix incorrect success and failure conditions in Kubeflow steps. 
The current conditions are incorrect.
No.
Tested in CI.

fix: Fix incorrect success and failure conditions in Kubeflow steps

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement_proposal.md

Add templates for bug reports and enhancements proposals.
To help community filing bugs and requesting featuers.
No.
No necessary.

docs: Add templates for bug reports and enhancements proposals

---

SECURITY.md

Add document on security policy. 
This defines how users should report security vulnerabilities for this repository that will be part of [the security overview of the project](https://github.com/couler-proj/couler/security).
No.
Not applicable.

docs: Add document on security policy

---

couler/argo.py
couler/core/templates/secret.py
couler/tests/secret_test.py

Allow to specify `name` and support `dry_run` for secrets.
To support SQLFlow's migration to Couler. They'd like to customize the name and avoid creating duplicated secrets.
cc @Yancey1989 @linkerzhang
New args are added: `name` and `dry_run`.
Tests are modified.

feat: Allow to specify name and support dry-run for secrets

---

couler/core/templates/workflow.py
couler/tests/cluster_config_test.py
couler/tests/test_data/dummy_cluster_config.py

Support cluster configuration at template and workflow level.
This is needed for integration with SQLFlow. cc @Yancey1989 @linkerzhang 
No, but adds `config_workflow` method that can be used to configure workflow-level spec.
Unit test added.

feat: Support cluster configuration at template and workflow level

---

couler/core/utils.py

Fix invalid name for different ways of invoking functions.
Fixes #103. This is similar to https://github.com/couler-proj/couler/pull/81 but a more generalized approach is introduced.
cc @linkerzhang @Yancey1989
No.

fix: Fix invalid name for different ways of invoking functions

---

couler/core/utils.py

Strip unnecessary <|> pattern in argo_safe_name().
This is similar to what's done in https://github.com/couler-proj/couler/pull/105 but for a more general case for names. Fixes #103. Previously this case was not considered. cc @linkerzhang @Yancey1989 @ywskycn 
No.

fix: Strip unnecessary <|> pattern in argo_safe_name()

---

couler/core/states.py
couler/core/step_update_utils.py
couler/core/syntax/conditional.py
couler/tests/dag_test.py
couler/tests/test_data/dag_golden_2.yaml

Support couler.when() in set_dependencies().
Users would like to specify conditions using `couler.when()` in a DAG.
No.
Added unit tests.

feat: Support couler.when() in set_dependencies()

---

integration_tests/dag_example.py

Add couler.when() step in DAG example for integration test.
This functionality was introduced in https://github.com/couler-proj/couler/pull/96 but was not tested in integration test. This ensures that the functionality works with Minikube.
No.
Integration test is modified.

ci: Add couler.when() step in DAG example for integration test

---

couler/argo.py

Delete the saved states of the workflow once submitted.
This change cleans up the saved states of the workflow since we made a copy of the workflow above and no longer need the original reference. This would also allow users to define a new workflow after submission. 
This would make it easier for Jupyter notebook users so any new templates created would not be appended to the previously created and already submitted templates. 
cc @inohmonton99

fix: Delete the saved states of the workflow once submitted

---

.github/workflows/build.yml

Upgrade Argo Workflows to v2.12.0-rc1.
To make sure Couler works with the latest version.
No.

ci: Upgrade Argo Workflows to v2.12.0-rc1

---

README.md
couler/core/step_update_utils.py
integration_tests/dag_example.py

This is a bug fix for dag dependencies. When you ran the diamond() example, it produced a dependency like the following
```
"name": "D",
"dependencies": [
"B",
[
"B"
]
],
```
This should be 
```
["B", "B"]
```
It also fixes the diamond example so the dependencies are B and C instead of B and B.
Please see above.
No.

fix: issue with dag multiple dependencies not formatting correctly

---

.github/workflows/build.yml

Opting into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.
Fix the following error observed in [this build](https://github.com/couler-proj/couler/pull/114/checks?check_run_id=1448660896):
```
Error: Unable to process command '::add-path::/home/runner/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
No.
Tested in CI.

ci: Fix GitHub Actions build due to recent deprecation

---

couler/core/templates/workflow.py

Guard config_pod with try-except to support args with default.
The try-except here is necessary in case the implementation of `config_pod` supports additional arguments with default values. This is to make sure that the older versions of cluster config files still work.
No.

fix: Guard config_pod with try-except to support args with default

---

couler/core/states.py
couler/core/step_update_utils.py
couler/core/syntax/dag.py
integration_tests/dag_depends_example.py
scripts/integration_tests.sh
scripts/validate_workflow_statuses.sh

Support enhanced depends logic for DAG dependencies in `couler.set_dependencies`. See details of enhanced depends logic in Argo here: https://github.com/argoproj/argo/blob/master/docs/enhanced-depends-logic.md
Users would like to specify the dependencies based on the statuses.
The `dependencies` argument in `set_dependencies()` can now accept a string that represents the enhanced depends logic.
Added to integration test.

feat: Support enhanced depends logic for DAG dependencies

---

.github/workflows/build.yml
.gitignore
proto/couler.proto
setup.py

Run `python setup.py proto` to generate proto python bindings.

feat: Add couler proto defs

---

couler/core/states.py
couler/core/syntax/dag.py
couler/tests/argo_test.py
couler/tests/argo_yaml_test.py
couler/tests/cluster_config_test.py
couler/tests/daemon_step_test.py
couler/tests/dag_test.py
couler/tests/env_test.py
couler/tests/katib_step_test.py
couler/tests/utils_test.py

fix: Handle None in couler.set_dependencies. Closes #118

---

couler/core/run_templates.py
couler/core/templates/container.py
couler/tests/argo_test.py
couler/tests/artifact_test.py
couler/tests/dag_test.py
couler/tests/run_concurrent_test.py
couler/tests/step_output_test.py
couler/tests/test_data/artifact_passing_golden.yaml
couler/tests/test_data/output_golden_1.yaml
couler/tests/test_data/output_golden_2.yaml
couler/tests/test_data/parameter_passing_golden.yaml

Automatically mount emptyDir volume for output artifacts to work with Argo k8sapi executor.
This is required to work with Argo k8sapi executor. More info on this pattern: https://argoproj.github.io/argo/empty-dir/
Mounting to base image layer `/tmp` is no longer supported.
Added unit test.

feat: Mount emptyDir volume for output artifacts to work with Argo k8sapi executor

---

proto/couler.proto

Add ContainerSpec and ResourceSpec to Step proto def.
K8s resource needs to be supported as well.
No.
Not tested.

feat: Add ContainerSpec and ResourceSpec to Step proto def

---

couler/core/step_update_utils.py
couler/tests/argo_test.py
couler/tests/dag_test.py

Add missing when condition for exit handler.
The when condition was missing previously.
No.
Added tests.

fix: Add missing when condition for exit handler

---

.github/workflows/build.yml
couler/core/proto_repr.py
couler/core/run_templates.py
couler/core/states.py
couler/core/utils.py
couler/tests/argo_test.py
couler/tests/proto_repr_test.py
requirements-dev.txt
setup.py

Generate protobuf representations when writing `couler.run_xxx` APIs.

feat: Add run_xxx generate proto representation

---

ADOPTERS.md

Removing us from adopters, thanks!

Remove myself from ADOPTERS.md

---

couler/core/proto_repr.py
couler/tests/proto_repr_test.py
go/couler/conversion/argo_workflow.go
go/couler/conversion/argo_workflow_test.go
go/couler/optimization/optimization_test.go
proto/couler.proto

Support concurrent steps proto representation.
To represent Argo concurrent steps.
No.
Unit tests were included.

feat: Support concurrent steps proto representation

---

proto/couler.proto

add action and owner_reference in ResourceSpec

feat: add action and owner reference in resource spec

---

.github/workflows/build.yml
go.mod
go.sum
go/couler/conversion/argo_workflow.go
go/couler/conversion/argo_workflow_test.go
go/couler/submitter/argo_submitter.go
go/couler/submitter/argo_submitter_test.go

Implement Argo workflow submitter in Go.
We need to submit the workflow once an Argo workflow has been constructed from the workflow IR.
Yes, `ConvertToArgoWorkflow` has been made public and new API `ArgoWorkflowSubmitter.Submit()` is added.
Added integration test in the CI to make sure the workflow can run successfully in Minikube.

feat: Implement Argo workflow submitter in Go

---

couler/core/proto_repr.py
couler/core/run_templates.py
couler/tests/proto_repr_test.py
proto/couler.proto

Seperate step template in proto
Steps need to call the step templates with args
No.
Unittest is included.

feat: Seperate step template in proto

---

go/couler/submitter/argo_submitter.go
go/couler/submitter/argo_submitter_test.go

Support submit Argo workflow without watching for completion.
This is helpful when users just want to submit the workflow without waiting for completion. Addressed the comment in https://github.com/couler-proj/couler/pull/136#discussion_r544554046.
Yes, new arg `watch` is added.
Additional test cases on the submitted workflow objects are added.

feat: Support submit Argo workflow without watching for completion

---

go.mod

Pin Go version to be consistent with internal version.

build: Pin Go version to be consistent

---

go/couler/submitter/argo_submitter.go
go/couler/submitter/argo_submitter_test.go

Print out status messages for workflow nodes for easier debugging.
Currently if the workflow has failed, it's hard to debug since there are no error messages for workflow and its nodes.
No.

feat: Propagate workflow status error message for failed/errored workflows

---

go/couler/submitter/argo_submitter.go

Add `New` function in argo submitter package.

feat: Add New func to return ArgoSubmitter object

---

.github/workflows/build.yml
go/couler/conversion/argo_workflow.go
go/couler/conversion/argo_workflow_test.go
go/couler/submitter/argo_submitter_test.go

This PR added support to convert from when conditions and exit handler steps in IR to part of the Argo Workflow that can be submitted. Additional tests are added.

feat: Support conversion of when condition and exit handler steps

---

couler/core/workflow_validation_utils.py
requirements-dev.txt
requirements.txt

Moving "argo-workflows" from a mandatory dependency requirement to an optional dependency.
To avoid installing a dependency when there is no necessity.
No.
No tests were added.

fix: moved argo-workflow to be an optional dependency

---

couler/core/proto_repr.py

Not using `append` for protobuf nested messages to support protobuf runtime version 3.7.1.
To be compatible with more protobuf installed version.
No.
The current unit tests can cover these changes.

feat: compatible with protobuf_371

---

README.md

Some context in https://github.com/couler-proj/couler/issues/165. Thanks @alexec! I also added some comments in the Google Doc of the draft. Please take a look when you get a chance as well.

doc: Add link to Argo blogpost on Python SDKs

---

.github/workflows/build.yml
.gitignore
couler/argo_submitter.py
go/couler/commands/submit.go
go/couler/submitter/argo_submitter.go
go/couler/submitter/argo_submitter_test.go
integration_tests/flip_coin_example.py

Support submitting workflow via Go implementation.
Allow us to submit workflow pb defined in Python via the Go implementation of submitter.
No. There's a new flag to toggle this but default behavior is the same.
Tests added.

feat: Support submitting workflow via Go implementation

---

couler/argo.py
couler/core/constants.py
couler/core/proto_repr.py
couler/core/run_templates.py
couler/core/step_update_utils.py
couler/core/templates/__init__.py
couler/core/templates/artifact.py
couler/core/templates/container.py
couler/core/templates/output.py
couler/core/templates/script.py
couler/steps/pod_utils.py
couler/tests/argo_test.py
couler/tests/artifact_test.py

This PR makes it so that `script` templates inherit from the `container` template and support all the fields that Argo supports.
We were not able to use the `script` template as is since a lot fields were missing.
Yes, the `script` template signature has additional arguments.
We made sure the current tests pass and this [use case](https://github.com/onepanelio/python-sdk/blob/8f178d78b8535e8d0d2c3c4244ce3dc33cb080f9/examples/python-defined-workflow.ipynb) for script templates is supported.

feat: Support all script template fields

---

couler/core/proto_repr.py
couler/core/run_templates.py
go/couler/conversion/argo_workflow.go
integration_tests/dag_example.py
integration_tests/flip_coin_example.py

This PR includes the following changes:
* Support IR conversion from DAG dependencies.
* Bug fixes for IR conversion from parameters/artifacts in DAG tasks.
* Make sure the existing DAG example can run on both Python and Go submitter.

feat: Support IR conversion from DAG dependencies

---

ADOPTERS.md

docs: Add SQLFlow to list of adopters

---

couler/_version.py

docs: Bump version to v0.1.1rc8

---

couler/argo.py
couler/core/run_templates.py
couler/core/templates/__init__.py
couler/core/templates/cache.py
couler/core/templates/container.py
couler/core/templates/script.py
couler/core/templates/template.py
integration_tests/memoization_example.py

feat: Support memoization cache in templates

---

ADOPTERS.md

Leaving the contact information here would have the risk of getting spammed from others. Removing them for now.

docs: Remove contact information to avoid spams

---

couler/core/run_templates.py

fix: Remove exception when mount path is /tmp

---

couler/core/proto_repr.py
couler/core/run_templates.py
couler/tests/proto_repr_test.py

fix: Add missing cache proto field when converting to workflow pb

---

couler/steps/tensorflow.py
couler/tests/tensorflow_step_test.py

Support evaluator in steps/tensorflow
Evaluator is an important role in tfjob. It is useful to do the evaluation in evaluator not in the worker.
So add evaluator in the step to support run tensorflow job with evaluator.
tensorflow step add evaluator configs, which is forward compatible.
unit test

feat: Step/Tensorflow support evaluator

---

README.md

docs: Add link to Katacode interactive course

---

README.md

chore: Fix links to Argo Workflows repo

---

README.md
integration_tests/dag_example.py

docs: More concise DAG example

---

ADOPTERS.md

docs: Add Konnecto to adopters

---

ADOPTERS.md

I think it's better to keep it as a comment in page source rather than something visible to all technical managers and their managers when a tech-sale to decision makers is being made :-)

docs: alphabetical order request in page source comment

---

couler/core/syntax/loop.py
couler/tests/map_test.py

Added changes to accept multiple function arguments in couler.map()
#169 continuing the fix adding the test function for the modifications.
**Had to start again from scratch.
Reason:** 
The previous idea just pretty much loops the arguments in the ```map()```.
```return map(map(function, input_list), *other)```
But the return value is a ```Step Class``` not a function so the first ```map()``` will succeed but not the second one or the third... because the ```map()``` checks the function first. 
```inner_step = Step(name=inner_dict["id"], template=template_name)```
```return inner_step```
#32  issue
#32  issue
No.
A test was created for it. similar to the one-argument test.
[Test](couler/tests/map_test.py)

fix: Support multiple function arguments in couler.map()

---

.github/workflows/build.yml

See context in https://github.com/argoproj/argo-workflows/issues/6464.

build: Fix invalid link to argo-workflows + temporarily disabled integration tests

---

couler/core/syntax/__init__.py
couler/core/syntax/dns.py
couler/core/templates/dns.py
couler/core/templates/workflow.py
couler/tests/argo_test.py

this change add dns py, and add related method in workflow.
our project need set dns config for workflow pod ,so i add this.
I think not, this is an new feature. It only affects when it is needed
I use one unit test to test my code.

feat:  add workflow spec dns support for python

---

couler/argo.py

This fixes https://github.com/couler-proj/couler/issues/248
In that issue, @merlintang mentions this section can be removed.
Since this code is not contained in a method, it ends up being called outside of the context of couler/argo.
Only the reduction of output.
Removed this and raised an exception and didn't get the yaml dump

feat: removing stray yaml dump

---

.github/workflows/build.yml
README.md

docs: Add notes regarding the status of Couler. Fixes #251

---

ADOPTERS.md

Creates new entry in the ADOPTERS.md file
Project support
Yes
N/A

Add PITS Globale Datenrettungsdienste as an adopter
